# Workflow Configuration

pipelines:
  branches:
    dev:
      - step:
          name: Build and Push image
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD $DOCKER_HUB_URL
            - docker build -t $DOCKER_IMAGE_NAME:dev_$BITBUCKET_BUILD_NUMBER .
            - docker push $DOCKER_IMAGE_NAME:dev_$BITBUCKET_BUILD_NUMBER
          services:
            - docker
      - step:
          name: Deploy to Stage
          deployment: Staging
          clone:
            enabled: false
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $SSH_SERVER_USER
                SERVER: $SSH_SERVER_IP
                COMMAND: >
                  docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD} $DOCKER_HUB_URL
                  && docker pull $DOCKER_IMAGE_NAME:dev_${BITBUCKET_BUILD_NUMBER}
                  && docker service update --image $DOCKER_IMAGE_NAME:dev_${BITBUCKET_BUILD_NUMBER} $SERVICE_DEV_NAME
    master:
      - step:
          name: Build and Push image
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD $DOCKER_HUB_URL
            - docker build -t $DOCKER_IMAGE_NAME:prod_$BITBUCKET_BUILD_NUMBER .
            - docker push $DOCKER_IMAGE_NAME:prod_$BITBUCKET_BUILD_NUMBER
          services:
            - docker
      - step:
          name: Deploy to Prod
          deployment: Production
          clone:
            enabled: false
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $PROD_SERVER_USER
                SERVER: $PROD_SERVER_IP
                COMMAND: >
                  docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD} $DOCKER_HUB_URL
                  && docker pull $DOCKER_IMAGE_NAME:prod_${BITBUCKET_BUILD_NUMBER}
                  && docker service update --image $DOCKER_IMAGE_NAME:prod_${BITBUCKET_BUILD_NUMBER} $SERVICE_MASTER_NAME
